Update Minio Swift Photo App for Xcode 8.3.3, Swift 3.1
minio/swift-photo-app pull request #14
Opened 2017-07-13 18:19 UTC by CarterMcClellan

Change Notes
----------------
Update xcode (8.3.3) and swift (3.1) version numbers

Update image for new project which we are creating (-> projectTemplate1.01)

Update MainStoryBoard image (-> storyBoard 1.01)

Remove “add missing contraints” 

Update and upload view controller.swift

Update (-> infoplst1.01) and upload Info.plist

2017-07-13 18:23 UTC, deekoder requested changes
One change requested.

2017-07-13 18:23 UTC, deekoder commented on README.md
> +        let url = URL(string: "http://play.minio.io/PhotoAPIService/minio/photoservice/list")
This needs to be the same as the url before. missing 0.0.1-SNAPSHOT

2017-07-13 18:35 UTC, deekoder requested changes
More changes are needed.

2017-07-13 18:35 UTC, deekoder commented on README.md
> +![minio_SWIFT2](docs/screenshots/projectTemplate1.01.png?raw=true)
Full image url is needed. Otherwise image wont show on docs.minio.io site.

2017-07-13 18:35 UTC, deekoder commented on README.md
> +![minio_SWIFT4](docs/screenshots/storyBoard1.01.png?raw=true)
same here

2017-07-13 18:35 UTC, deekoder commented on README.md
> +        let url = URL(string: "http://play.minio.io/PhotoAPIService-0.0.1-SNAPSHOT/minio/photoservice/list")
i think you should make sure this URL is where harsha will deploy. I am wondering if we left http and are only https now.

2017-07-13 18:35 UTC, deekoder commented on README.md
> +![minio_SWIFT6](docs/screenshots/infoplst1.01.png?raw=true)
fix path

2017-07-13 18:35 UTC, deekoder commented on SwiftPhotoApp/ViewController.swift
> +        let url = URL(string: "http://play.minio.io/PhotoAPIService/minio/photoservice/list")
Same here. Need the version and confirmation whether its http or https

2017-07-15 00:32 UTC, harshavardhana requested changes

2017-07-15 00:32 UTC, harshavardhana commented on README.md
> +![minio_SWIFT6](https://github.com/minio/swift-photo-app/blob/master/docs/screenshots/infoplst1.01.png?raw=true)
While we are at it we should purge the old images in this PR.

2017-07-15 00:32 UTC, harshavardhana commented on SwiftPhotoApp/ViewController.swift
> +        let url = URL(string: "http://play.minio.io/PhotoAPIService/minio/photoservice/list")
Its http. @CarterMcClellan

2017-07-17 23:33 UTC, closed without merging